In [3]:
import numpy as np
print(np.arange(5))
print(np.arange(1,5))
print(np.arange(0,10,2))

[0 1 2 3 4]
[1 2 3 4]
[0 2 4 6 8]


In [6]:
print(np.linspace(0,1,5))
print(np.zeros(5))
print(np.ones(5))

[0.   0.25 0.5  0.75 1.  ]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [15]:
X = np.random.randn(5)
Y = np.random.randn(5)
print(X)
print(Y)
np.random.seed(0)
X = np.random.randn(5)
np.random.seed(0)
Y = np.random.randn(5)
print('X (seed=0):', X)
print('Y (seed=0):', Y)

[1.76405235 0.40015721 0.97873798 2.2408932  1.86755799]
[-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
X (seed=0): [1.76405235 0.40015721 0.97873798 2.2408932  1.86755799]
Y (seed=0): [1.76405235 0.40015721 0.97873798 2.2408932  1.86755799]


In [20]:
arr1 = np.random.randint(0,11,(5,2)) # 在0~10範圍中，生成出5列2行的matrix
print(arr1)

arr2 = np.random.rand(3) # 生成在 [0, 1) 之間均勻分布的隨機浮點數，形狀為 (3, 3)
print(arr2)

[[3 8]
 [1 3]
 [3 3]
 [7 0]
 [1 9]]
[0.53737323 0.75861562 0.10590761]


In [23]:
np.random.seed(0) # 設定隨機種子，可確保隨機產生的結果是可重複的
X = ['蘋果', '橘子', '香蕉', '鳳梨', '奇異果', '草莓']
print(np.random.choice(X,5))

['奇異果' '草莓' '蘋果' '鳳梨' '鳳梨']


In [24]:
# Python變數是指向相同的記憶體位置
arr1 = np.array([1, 2, 3, 4, 5])
print('arr1:'+str(arr1))
arr2 = arr1
arr2[0] = 100
print('arr2:'+str(arr1))
print('arr1:'+str(arr2)) # 跟著連動

arr1:[1 2 3 4 5]
arr2:[100   2   3   4   5]
arr1:[100   2   3   4   5]


In [25]:
# 避免連動
arr1 = np.array([1, 2, 3, 4, 5])
print('arr1:'+str(arr1))
arr2 = arr1.copy()
arr2[0] = 100
print('arr2:'+str(arr1))
print('arr1:'+str(arr2)) 

arr1:[1 2 3 4 5]
arr2:[1 2 3 4 5]
arr1:[100   2   3   4   5]


In [28]:
arr = np.arange(10)
print(arr)
arr[0:3] = 1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 1 1 3 4 5 6 7 8 9]


In [31]:
s = [1,2,3,4]
new = []
for i in s:
    i += i
    new.append(i)
print(new)

[2, 4, 6, 8]


In [33]:
s = np.array([1,2,3,4])
s += s
print(s)

[2 4 6 8]


In [36]:
arr = np.array([4, -9, 16, -4, 20])
print(arr)

arr_abs = np.abs(arr)
print(arr_abs)
print(np.exp(arr_abs)) # e為底
print(np.sqrt(arr_abs)) # 平方根

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


In [42]:
arr1 = np.array([2, 5, 7, 9, 5, 2])
arr2 = np.array([2, 5, 8, 3, 1])
new = np.unique(arr1) # 刪除重複
print(new)

print(np.union1d(new,arr2)) # 取聯集
print(np.intersect1d(new,arr2)) # 取交集
print(np.setdiff1d(new,arr2)) # 取差集

[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


In [45]:
arr = np.array([ [1, 2 ,3],[4, 5, 6]])
print(arr.sum())
print(arr.sum(axis=0)) # columns:0 相加
print(arr.sum(axis=1)) # row:1 相加

21
[5 7 9]
[ 6 15]


In [46]:
arr = np.array([[[0,1,2],[3,4,5]],
[[6,7,8],[9,10,11]]])
print(arr.sum())

66


In [47]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [49]:
print(arr.sum(axis=0))
print(arr.sum(axis=1))


[[ 6  8 10]
 [12 14 16]]
[[ 3  5  7]
 [15 17 19]]


In [51]:
arr = np.arange(10).reshape(2,5)
print(arr)

print(arr.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [53]:
arr = np.array([[8, 4, 2],[3, 5, 1]])

print(np.sort(arr))
arr.sort(axis=0) # column為主:對每一個column進行排序 eg. [8,3]變[3,8]
print(arr)

[[2 4 8]
 [1 3 5]]
[[3 4 1]
 [8 5 2]]


In [54]:
print(arr.argsort()) # 回傳由小到大數值排列的索引值

[[2 0 1]
 [2 1 0]]


In [57]:
x = np.arange(15).reshape(3, 5)
print(x)
y = np.array([np.arange(5)])
print(y)

z = x - y
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2 3 4]]
[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]
