In [1]:
import torch
a = torch.ones(3)  # 創建一個三維的一軸向量
a

tensor([1., 1., 1.])

In [2]:
a[1]

tensor(1.)

In [3]:
float(a[1])

1.0

In [4]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [6]:
points = torch.ones(4)  # 法1
points[0] = 4.0     # 點A的X座標
points[1] = 1.0     # 點A的Y座標
points[2] = 3.0     # 點B的X座標
points[3] = 6.0     # 點B的Y座標

points

tensor([4., 1., 3., 6.])

In [7]:
p = torch.tensor([4.0, 1.0, 3.0, 6.0])   # 法2
p

tensor([4., 1., 3., 6.])

In [13]:
### 提取點座標
float(points[0]),float(points[1])

(4.0, 1.0)

In [14]:
### 提取點座標
float(points[0]),float(points[1]),float(points[2])

(4.0, 1.0, 3.0)

In [16]:
#　二軸張量
points = torch.tensor([[4.0, 1.0],[5.0,3.0],[2.0,1.0]])
points[0]

tensor([4., 1.])

In [17]:
# 利用張量的shape屬性，查詢其大小
points.shape

torch.Size([3, 2])

In [18]:
p = torch.zeros(3,2)
p

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
#　二軸張量
points = torch.tensor([[4.0, 1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [21]:
points[1:,0]

tensor([5., 2.])

In [25]:
# 替Tensor命名
weight_name = torch.tensor([0.2731,0.3413,0.2523],names=['channels'])
weight_name

C:\Users\yifun\AppData\Local\Temp\ipykernel_8628\3974000915.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10/core/TensorImpl.h:1791.)
  weight_name = torch.tensor([0.2731,0.3413,0.2523],names=['channels'])


tensor([0.2731, 0.3413, 0.2523], names=('channels',))

2.0.1+cpu
