In [2]:
import torch
a = torch.ones(3)  # 創建一個三維的一軸向量
a

tensor([1., 1., 1.])

In [2]:
a[1]

tensor(1.)

In [3]:
float(a[1])

1.0

In [4]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [6]:
points = torch.ones(4)  # 法1
points[0] = 4.0     # 點A的X座標
points[1] = 1.0     # 點A的Y座標
points[2] = 3.0     # 點B的X座標
points[3] = 6.0     # 點B的Y座標

points

tensor([4., 1., 3., 6.])

In [7]:
p = torch.tensor([4.0, 1.0, 3.0, 6.0])   # 法2
p

tensor([4., 1., 3., 6.])

In [13]:
### 提取點座標
float(points[0]),float(points[1])

(4.0, 1.0)

In [14]:
### 提取點座標
float(points[0]),float(points[1]),float(points[2])

(4.0, 1.0, 3.0)

In [16]:
#　二軸張量
points = torch.tensor([[4.0, 1.0],[5.0,3.0],[2.0,1.0]])
points[0]

tensor([4., 1.])

In [17]:
# 利用張量的shape屬性，查詢其大小
points.shape

torch.Size([3, 2])

In [18]:
p = torch.zeros(3,2)
p

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
#　二軸張量
points = torch.tensor([[4.0, 1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [21]:
points[1:,0]

tensor([5., 2.])

In [4]:
# 替Tensor命名
weight_name = torch.tensor([0.2731,0.3413,0.2523],names=['channels'])
weight_name

tensor([0.2731, 0.3413, 0.2523], names=('channels',))

In [3]:
img_t = torch.randn(3,5,5)     # 創3軸張量
batch_t = torch.randn(2,3,5,5) # 創4軸張量
img_name = img_t.refine_names(..., 'channels','rows','columns') # 省略其他軸，只針對張量的最後3個軸去命名
batch_name = batch_t.refine_names(..., 'channels','rows','columns')

print('img named:',img_name.shape,img_name.names)
print('batch name:',batch_name.shape,batch_name.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch name: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


#### 使用align_as()會自動添加缺失的軸

In [5]:
w_aligned = weight_name.align_as(img_name)
w_aligned.shape, w_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [6]:
gray_named = (img_name * w_aligned).sum('channels')

gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

#### 設定資料型別

In [7]:
double_points = torch.ones(10,2,dtype=torch.double)
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [9]:
short_points = torch.tensor([[1,2],[3,4]],dtype=torch.short)
short_points.dtype

torch.int16

In [13]:
d = torch.zeros(10,2).double()
print(d.dtype)

s = torch.ones(10,2).short()
print(s.dtype)

torch.float64
torch.int16


In [14]:
p_64 = torch.zeros(5,dtype=torch.double)
p_short = p_64.to(torch.short)
p_64 * p_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [16]:
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)  # 將a張量的第0軸和第1軸進行轉置
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [17]:
# 透過張量的method進行轉置
a = torch.ones(3,2)
a_t = a.transpose(0,1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [18]:
p = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
p.storage() # 永遠是一軸的，連續儲存空間

C:\Users\yifun\AppData\Local\Temp\ipykernel_3576\3058080218.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  p.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [19]:
pp = p.storage()
pp[0]

4.0

In [20]:
p.storage()[1]

1.0

In [21]:
p = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
pp = p.storage()
pp[0] = 99
p

tensor([[99.,  1.],
        [ 5.,  3.],
        [ 2.,  1.]])

In [22]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [23]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [24]:
p = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
p.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [25]:
sec = p[1]
sec.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [26]:
sec.storage_offset()

2

In [27]:
sec.size()

torch.Size([2])

In [29]:
sec.shape

torch.Size([2])

In [31]:
p.stride()

(2, 1)

In [32]:
p = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
sec = p[1].clone() # 複製

sec[0] = 20000
p

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [3]:
p = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
p

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [5]:
p_t = p.t()
p_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [7]:
id(p.storage()) == id(p_t.storage()) # 是否共用同個storage

C:\Users\yifun\AppData\Local\Temp\ipykernel_2024\25068764.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  id(p.storage()) == id(p_t.storage())


True

In [8]:
p.stride()

(2, 1)

In [9]:
p_t.stride()

(1, 2)

In [10]:
some_t = torch.ones(3,4,5)
some_t.shape

torch.Size([3, 4, 5])

In [11]:
transpose_t = some_t.transpose(0,2) # 將第0軸和第2軸對調
transpose_t.shape

torch.Size([5, 4, 3])

In [14]:
some_t.stride()

(20, 5, 1)

In [15]:
p.is_contiguous()

True

In [16]:
p_t.is_contiguous()

False

In [17]:
p_gpu = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]],device='cuda')
p_gpu

AssertionError: Torch not compiled with CUDA enabled

In [19]:
p = torch.ones(3,4)
p_np = p.numpy() # 轉成numpy array
p_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [20]:
torch.save(p,'our.t')

In [21]:
with open('our.t','wb') as f:
    torch.save(p,f)

In [23]:
ppp = torch.load('our.t')
ppp

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
p = torch.ones(3,4)


In [32]:
import h5py
f = h5py.File('ourr.hdf5','w')
dset = f.create_dataset('coords',data=p.numpy())
f.close()

In [33]:
f = h5py.File('ourr.hdf5','r')
dset = f['coords']
last_p = dset[-2:]

In [34]:
last_p

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)